import Head from 'next/head';
import { useQuery } from 'react-query';
import axios from 'axios';
import 'ebs-design/dist/styles/index.scss';
import { Chart } from '../components/organisms/Chart/Chart';
import { Table } from '../components/organisms/Table/Table';

export default function Home() {
  const url = `https://api.openweathermap.org/data/2.5/forecast?lat=${47.00367}&lon=${28.907089}&cnt=5&appid=89513552b4f105442d50d8ea3bea505d&units=metric`;

  const { data } = useQuery('weather', () =>
    axios.get(url).then((response) => response.data)
  );

  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='main'>
        <Chart data={data} />
        <Table data={data} />
      </main>
    </div>
  );
}
