import Head from 'next/head';
import Image from 'next/image';
import { useQuery } from 'react-query';
import axios from 'axios';
import styles from '../styles/Home.module.css';

export default function Home() {
  const url = `https://api.openweathermap.org/data/2.5/weather?lat=${47.00367}&lon=${28.907089}&appid=89513552b4f105442d50d8ea3bea505d`;

  const { data } = useQuery('weather', () =>
    axios.get(url).then((response) => response.data)
  );
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>hello</h1>
    </div>
  );
}
